jobs:
  include:
    - language: node_js
      node_js:
        - '12'
      script:
        - "./dump_napituti.sh"
      branches:
        only:
          - develop
      deploy:
        provider: s3
        access_key_id:
          secure: eILvMZKJZiyUIWD0a1NEPC/ERSLsHPu/9dzWEPI3m8ul6PQSfzhXLF0tSHeIbeNrX0bnotyPfIFYshJRGNhTtmwNEvC9EDAmdfRpntk+xLWSYqxO3eJEWrqY6FcM10rELPxcFhR7P17wzp5daKF/Dsg1Ayxoh+O4dha/EAuG2uA0vCjII0ea6BbeLkPTAhLV+i5dlv0TFUBScthDCbCFOf978W5kNTsAZYBOiLhmqDGX3kG5DyjdJeUKtzvG5b60q+IVk6EXOegV7AzC3UUFItQikSxNiWasDMubzNaiMVqx37qn5IKm5eoHZOUO+PNUm5E1O+9myXq9H2bLFmsyS5dmuxes8K8CEyZWHzpRh7eSrv3D1A9epngm01+SR1YWecIZJAmXzqG2yNdQhxGOdMhK/vP+M+mxD0vubPA/72oR9GCl1HcpXreZO8nCJHMBqdSCqP9Z98+eX0D0QIoNh0sWijQxXRQvARmrOonwQYfRgV5CxKRvc3OQWveuuhRJNrxxHEMRVyxSW+POBXXTHhrh9Ywz2n22mgjHHxVKGRMhdRaD3GowtEwQ5xHi/VlgeEe6jLdefW+bzgjDCaT8bAH1ETrtaHs8vZSdwFszSMtY6Kp0eUODi+JmKeEloNGg9OIehGmk028qHdS6/yYrsFacSxeUE7UXUjb3sXMtsQ8=
        secret_access_key:
          secure: eKM9pblfd8KtWfSGSwelLA731rhMEZw+JUlv5gBlnTAEy2Zvjccp2xmmmKWyIy+BiwpJUACc0F0UGKk3zzHy9Wuw3nvyf8+6IBBClN2k+QUX8DeqfRv3PYCxDMJ+OeqA7CCujZm6Vnlx0BB8mqg5ySDb9jh9Jfscj0r6Mcz5fnlzJhHYQ7xS9/bd1YWtajgFMLoqR/O72v6G/yc9dx9BBKMYMsIRbJ1+lvCHO7nuiguoBp64IcuUyMPUGh2TJADXpTjByLiDGePmWefprR2i8MT50Lq6j4Ce3ujnL0Q/oIPWG++cl0tyXsUQduPVW4IOlXZqB7KPvKuBKpZk+abSvOd40xnNTctCqjgXQ94ZXiTCjZKxhyHV8gwz3dowPW1PywG1XpNoa5zGxN2q4AtYBzYqHDCYIR10W+Tb7fghEl3wH+0/s2MHwjDHKT/BPQVNAlPgCCrxro/p6fj+/C/Ss+SJW4Z9b8QDylCkDNdMYdY1tjKZu8rSCTtqBqZQJ2o+rl3KilvqnfeOBxVsnpG5jjaFksccnkSNl5GeWTLksp2m37+bPL4vk2MmQD0OkzHiAM0b928uzUcCfCKv/OalJf/M1/sDveSYx/S/Cg6ulAIFVfTic010nArUUcqvIsShYUPIS2DIOfZrL5ynp0l9LdpFfYJ767ku4UpycJSZxkY=
        bucket: napipatrik
        region: eu-west-1
      env:
        global:
          secure: pwnp9z6t1HQyjko6W9IYyXouMtX2QpRjzeIsksp7zDRTcuxyUW45KVKY7M1OfX5PZArQHqnc10zv3ae2DnL156FIjCXxcuuqDDmMZt/77re8T99upj5gR9twRFNVruPP/H1JyZ/pfR/LHBp2qgSdkvzfWfKbjq2rzmupg1GguAjhfm9ErcZhmfa/q1oRi4WB4Fa9Ict1TVHlm5WO0Slactm5COJUZQVfLlwhotHrX8ShdXJ9zSQJhZPZzt/WXdD2Ixz8tyio5WfrJWKgjP98Lh1/T4KcIvwXrbnT0fmFYEHL17ASw2cgRIIfmnKJZFZ1UTAI6BJgC0eIqz50F5aDrliBLpHnw1H+8Ld1vo4WdFP1VoeyU0HXM/mT4OB4teeew3p536WvIwWA0J9ioLgTnNdTWfZx85H0RJGwkVqc+S7enNmZk/hnNohnbrVLQEX4r7MAttdT2lg4xfSndNL1rePY0m119wCtU75I1NqFSX4l/YMI5m8Rg4NWzsH+6oHnAYLutKvQJjRJv3JltXLVTOw/UlpsGMzNAmWx7UbfWVXPRLELifCDunXdLtpQ7npMY9ZfmdLl4Rh/3WpSsARVRE6LM1bN/hncNK5JDOj2NpoOeXKGElunRFoN1LwLiYADNIjbwlhbPQEnyJRwyBseKpMAgd1cFGO146wmjv3TrdA=

    - language: ruby
      cache: bundler
      branches:
        only:
          - develop
      script:
        - JEKYLL_ENV=production bundle exec jekyll build --destination site
      deploy:
        provider: pages
        local_dir: ./site
        target_branch: master
        email: deploy@travis-ci.org
        name: Deployment Bot
        cleanup: false
        token: $GH_TOKEN
        keep_history: true
        on:
          branch: develop
      env:
        global:
          secure: pwnp9z6t1HQyjko6W9IYyXouMtX2QpRjzeIsksp7zDRTcuxyUW45KVKY7M1OfX5PZArQHqnc10zv3ae2DnL156FIjCXxcuuqDDmMZt/77re8T99upj5gR9twRFNVruPP/H1JyZ/pfR/LHBp2qgSdkvzfWfKbjq2rzmupg1GguAjhfm9ErcZhmfa/q1oRi4WB4Fa9Ict1TVHlm5WO0Slactm5COJUZQVfLlwhotHrX8ShdXJ9zSQJhZPZzt/WXdD2Ixz8tyio5WfrJWKgjP98Lh1/T4KcIvwXrbnT0fmFYEHL17ASw2cgRIIfmnKJZFZ1UTAI6BJgC0eIqz50F5aDrliBLpHnw1H+8Ld1vo4WdFP1VoeyU0HXM/mT4OB4teeew3p536WvIwWA0J9ioLgTnNdTWfZx85H0RJGwkVqc+S7enNmZk/hnNohnbrVLQEX4r7MAttdT2lg4xfSndNL1rePY0m119wCtU75I1NqFSX4l/YMI5m8Rg4NWzsH+6oHnAYLutKvQJjRJv3JltXLVTOw/UlpsGMzNAmWx7UbfWVXPRLELifCDunXdLtpQ7npMY9ZfmdLl4Rh/3WpSsARVRE6LM1bN/hncNK5JDOj2NpoOeXKGElunRFoN1LwLiYADNIjbwlhbPQEnyJRwyBseKpMAgd1cFGO146wmjv3TrdA=
