name: Build docker image

on:
  push:
    branches:
      - develop

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            discordbot:
              - 'discordbot/**'
      - name: Set up Docker Buildx
        if: steps.changes.outputs.discordbot == 'true'
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: steps.changes.outputs.discordbot == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps.changes.outputs.discordbot == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./discordbot
          push: true
          tags: rutkai/napipatrik-discordbot:latest
